#!/bin/bash
/path/to/your/python /path/to/your/main.py \
--username <username> \
--password <password> \
--mail_user <mail_user> \
--mail_pass <mail_pass> \
--location 中国江苏省南京市栖霞区仙林大道 \
--b64 \
--force \
--mail_notify